version: '3.1'

services:

  mysqldatabase:
    build:
      context: dockerfiles
      dockerfile: Dockerfile
    restart: always
    image: mysq8
    container_name: mysql-db-local
    volumes:
      - ~/.local_database/mysql8db/mysqlfordev:/var/lib/mysql
    ports:
      - 3306:3306
